"""Seed RBAC registry for tests.

Mirrors the platform's seeded catalog (identical to the API's day-1 seed) so the
dynamic, DB-driven registry the Layer B gate reads is populated deterministically
in unit tests, without a running control plane.
"""

from __future__ import annotations

from at_sql_analyser.authz.rbac_registry import CapabilityDescriptor, RbacRegistry


def _cap(
    capability_id: str,
    kind: str,
    mode: str,
    required: tuple[str, ...],
    risk: str,
    *,
    resource_scoped: bool,
    delegated: bool,
) -> CapabilityDescriptor:
    return CapabilityDescriptor(
        id=capability_id,
        kind=kind,
        mode=mode,
        required_permissions=required,
        risk=risk,
        resource_scoped=resource_scoped,
        delegated=delegated,
        enabled=True,
    )


SEED_CAPABILITIES: tuple[CapabilityDescriptor, ...] = (
    _cap(
        "sales.report.customer",
        "agent-skill",
        "read",
        ("read-sales", "read-customers"),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "sales.products.forCustomer",
        "agent-skill",
        "read",
        ("read-sales", "read-customers"),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "sales.create",
        "agent-skill",
        "write",
        ("write-sales",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "issues.list.pendingForCustomer",
        "agent-skill",
        "read",
        ("read-issues", "read-customers"),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "actions.next",
        "agent-skill",
        "read",
        ("read-actions",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "actions.markCompleted",
        "agent-skill",
        "write",
        ("write-actions",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "issues.create",
        "agent-skill",
        "write",
        ("create-issues",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "sop.read",
        "agent-skill",
        "read",
        ("read-sop",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "customers.search",
        "agent-skill",
        "read",
        ("read-customers",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "customers.get",
        "agent-skill",
        "read",
        ("read-customers",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "products.search",
        "agent-skill",
        "read",
        ("read-sales",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "products.get",
        "agent-skill",
        "read",
        ("read-sales",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "sales.list",
        "agent-skill",
        "read",
        ("read-sales",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "sales.get",
        "agent-skill",
        "read",
        ("read-sales",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "issues.list",
        "agent-skill",
        "read",
        ("read-issues",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "issues.get",
        "agent-skill",
        "read",
        ("read-issues",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "actions.list",
        "agent-skill",
        "read",
        ("read-actions",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "actions.get",
        "agent-skill",
        "read",
        ("read-actions",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "actions.addComment",
        "agent-skill",
        "write",
        ("write-actions",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "actions.update",
        "agent-skill",
        "write",
        ("write-actions",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "issues.update",
        "agent-skill",
        "write",
        ("write-issues",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "sop.create",
        "agent-skill",
        "write",
        ("write-sop",),
        "low",
        resource_scoped=False,
        delegated=True,
    ),
    _cap(
        "sop.update",
        "agent-skill",
        "write",
        ("write-sop",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "sop.addVersion",
        "agent-skill",
        "write",
        ("write-sop",),
        "low",
        resource_scoped=True,
        delegated=True,
    ),
    _cap(
        "data.schema.describe",
        "mcp-tool",
        "read",
        ("create-agent-run",),
        "low",
        resource_scoped=False,
        delegated=False,
    ),
    _cap(
        "data.query.select",
        "mcp-tool",
        "read",
        ("create-agent-run",),
        "low",
        resource_scoped=True,
        delegated=False,
    ),
    _cap(
        "data.analyse.read",
        "agent-skill",
        "read",
        ("create-agent-run",),
        "low",
        resource_scoped=True,
        delegated=False,
    ),
    _cap(
        "data.act.write",
        "agent-skill",
        "write",
        ("create-agent-run",),
        "high",
        resource_scoped=True,
        delegated=False,
    ),
)


SEED_ROLE_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "sales-user": (
        "read-customers",
        "write-customers",
        "read-issues",
        "read-sales",
        "write-sales",
        "read-actions",
        "read-sop",
        "create-agent-run",
        "read-agent-run",
        "cancel-agent-run",
    ),
    "support-operations-user": (
        "read-customers",
        "write-customers",
        "read-issues",
        "write-issues",
        "read-sales",
        "read-actions",
        "write-actions",
        "read-sop",
        "create-agent-run",
        "read-agent-run",
        "cancel-agent-run",
    ),
    "admin": (
        "read-customers",
        "write-customers",
        "create-issues",
        "read-issues",
        "write-issues",
        "read-sales",
        "write-sales",
        "read-permissions",
        "write-permissions",
        "read-actions",
        "write-actions",
        "read-sop",
        "write-sop",
        "read-users",
        "write-users",
        "create-agent-run",
        "read-agent-run",
        "cancel-agent-run",
    ),
    "customer-support": (
        "read-customers",
        "create-issues",
        "read-issues",
        "write-issues",
        "read-sales",
        "read-actions",
        "write-actions",
        "create-agent-run",
        "read-agent-run",
        "cancel-agent-run",
    ),
    "ops-compliance": (
        "read-sop",
        "write-sop",
        "create-agent-run",
        "read-agent-run",
        "cancel-agent-run",
    ),
}


def build_seed_registry() -> RbacRegistry:
    return RbacRegistry(
        revision=1,
        capabilities=SEED_CAPABILITIES,
        role_permissions=SEED_ROLE_PERMISSIONS,
    )
